# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 461478108f57c0e4a4df7f6556fd69bafc6c81e60308942ffff84222d137117de3c75a31811f82bb923a84d8a6dba2f3d7f44cad36ae4dfd77d42463e25fde78

test:
  secret_key_base: 07165a641263b297f91f6623fe69142b1387bd2ebb23603348572bb47b2a0ac065bc228b90ef0572f4ecb53ee1ed6e9133f7699e15ee4c9f7e0f37078c9bdc42

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
